name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
    inputs:
      directory:
        description: 'The directory containing the Dockerfile'
        required: true
        type: string
      tag:
        description: 'The Docker image tag'
        required: true
        type: string
      generate_dockerfile:
        description: 'Run generate_dockerfile_initdb.sh script'
        required: false
        type: boolean
        default: true
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build-and-push:
    strategy:
      matrix:
        postgres_version: [12, 13, 14, 15, 16, 17]
        variant: [dbo, pgtap, pgcrypto, latest]
    uses: SirSplat/workflows/.github/workflows/build-and-push-docker-image.yaml@main
    with:
      directory: ${{ inputs.directory }}
      tag: ${{ inputs.tag }}-${{ matrix.postgres_version }}-${{ matrix.variant }}
      image_name: postgresql
      postgres_version: ${{ matrix.postgres_version }}
      variant: ${{ matrix.variant }}
      generate_dockerfile: ${{ inputs.generate_dockerfile }}
      runner_debug: false
      step_debug: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}