name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
    inputs:
      directory:
        description: 'The directory containing the Dockerfile'
        required: true
        type: string
      tag:
        description: 'The Docker image tag'
        required: true
        type: string
      postgres_version:
        description: 'The PostgreSQL version'
        required: true
        type: string
      generate_dockerfile:
        description: 'Run generate_dockerfile_initdb.sh script'
        required: false
        type: boolean
        default: true
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build-and-push:
    uses: SirSplat/workflows/.github/workflows/build-and-push-docker-image.yaml@main
    with:
      directory: ${{ inputs.directory }}
      tag: ${{ inputs.tag }}-${{ inputs.postgres_version }}
      image_name: postgresql
      POSTGRES_VERSION: ${{ inputs.postgres_version }}
      generate_dockerfile: ${{ inputs.generate_dockerfile }}
      runner_debug: false
      step_debug: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

