name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'dbo/Dockerfile'
      - 'dbo/initdb.sh'
      - 'latest/Dockerfile'
      - 'latest/initdb.sh'
      - 'pgcrypto/Dockerfile'
      - 'pgcrypto/initdb.sh'
      - 'pgtap/Dockerfile'
      - 'pgtap/initdb.sh'
  pull_request:
    branches:
      - main
    paths:
      - 'dbo/Dockerfile'
      - 'dbo/initdb.sh'
      - 'latest/Dockerfile'
      - 'latest/initdb.sh'
      - 'pgcrypto/Dockerfile'
      - 'pgcrypto/initdb.sh'
      - 'pgtap/Dockerfile'
      - 'pgtap/initdb.sh'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dockerfile:
          - dbo/Dockerfile
          - latest/Dockerfile
          - pgcrypto/Dockerfile
          - pgtap/Dockerfile
        directory:
          - dbo
          - latest
          - pgcrypto
          - pgtap

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      if: |
        contains(github.event.head_commit.message, 'dbo/Dockerfile') || contains(github.event.head_commit.message, 'dbo/initdb.sh') ||
        contains(github.event.head_commit.message, 'latest/Dockerfile') || contains(github.event.head_commit.message, 'latest/initdb.sh') ||
        contains(github.event.head_commit.message, 'pgcrypto/Dockerfile') || contains(github.event.head_commit.message, 'pgcrypto/initdb.sh') ||
        contains(github.event.head_commit.message, 'pgtap/Dockerfile') || contains(github.event.head_commit.message, 'pgtap/initdb.sh')
      uses: docker/build-push-action@v6
      with:
        context: ./${{ matrix.directory }}
        file: ./${{ matrix.dockerfile }}
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/postgresql:${{ matrix.directory }}
        platforms: linux/amd64,linux/arm64