name: Build and Push latest Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'latest/Dockerfile'
      - 'latest/initdb.sh'
  pull_request:
    branches:
      - main
    paths:
      - 'latest/Dockerfile'
      - 'latest/initdb.sh'
  workflow_dispatch:

jobs:
  build-and-push:
    uses: SirSplat/workflows/.github/workflows/build-and-push-docker-image.yaml@main
    with:
      directory: ./latest
      tag: latest
      image_name: postgresql
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}