name: Build and Push latest Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'latest/Dockerfile'
      - 'latest/initdb.sh'
  pull_request:
    branches:
      - main
    paths:
      - 'latest/Dockerfile'
      - 'latest/initdb.sh'
  # Manually trigger the workflow from the Actions tab
  workflow_dispatch:
  # Schedule the workflow to run every Sunday at midnight
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build-and-push:
    # Make use of the shared workflow
    uses: SirSplat/workflows/.github/workflows/build-and-push-docker-image.yaml@main
    with:
      directory: ./latest
      tag: latest
      image_name: postgresql
      # Optional flags to enable workflow and step debugging
      runner_debug: false
      step_debug: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}