name: Build and Push pgcrypto Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'pgcrypto/Dockerfile'
      - 'pgcrypto/initdb.sh'
  pull_request:
    branches:
      - main
    paths:
      - 'pgcrypto/Dockerfile'
      - 'pgcrypto/initdb.sh'
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/build-and-push-docker-image.yaml
    with:
      directory: ./pgcrypto
      tag: pgcrypto