name: Build and Push pgtap Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'pgtap/Dockerfile'
      - 'pgtap/initdb.sh'
  pull_request:
    branches:
      - main
    paths:
      - 'pgtap/Dockerfile'
      - 'pgtap/initdb.sh'
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/build-and-push-docker-image.yaml
    with:
      directory: ./pgtap
      tag: pgtap
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}